# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: contact me on <a href="https://facebook.com/johnsniff443">facebook</a>

style: dark

plugins:
  - jekyll-seo-tag
